catalogs:
  prod:
    '@vill-v/type-as': ^2.0.1
    '@vill-v/ts': ^2.0.0
    '@vill-v/vanilla': ^2.0.0
    '@void-cache/storage-like': 0.1.3
  dev:
    '@types/node': ^22.15.33
    '@vill-v/bumpp-github': ^4.0.0
    '@vill-v/eslint-config': ^3.3.1
    '@vill-v/prettier-config': ^1.0.0
    '@vill-v/tsconfig': ^1.0.1
    eslint: ^9.29.0
    prettier: ^3.6.2
    publint: ^0.3.12
    tsdown: ^0.12.9
    typescript: ^5.8.3
    unplugin-unused: ^0.5.1
    '@oxc-project/runtime': ^0.75.0

onlyBuiltDependencies:
  - unrs-resolver
